### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#15]
Currently it is not possible to boot Windows using OC Boot menu ( At least for me, additional reports are welcome ). This shall  be fixed  with newer revisions of this EFI. Because one can boot using F12 Boot menu, it is currently a low priority task.

**Comment by zombillano** [comment]
I believe this is something related to OpenCore itself, not with this specific config. I'm doing dualboot using the same SSD for both windows and MacOS. I use refind to solve this problem, but would be nice to have bootcamp-like behaviour. I tried to install Windows 10 using bootcamp, without any success, even after modifying config.plist file acording to opencore manual.

**Comment by EETagent** [comment]
Do not know where is the problem. With ACPI patches probably not, as those that could be the cause are alredy patched with` If (_OSI ("Darwin")) {} `

**Comment by zombillano** [comment]
> Do not know where is the problem. With ACPI patches probably not, as those that could be the cause are already patched with`If (_OSI ("Darwin")) {}` check.

Yup. There's also an option on config.plist that supossely disable ACPI when booting on a OS that isn't macOS, but that didn't work to me. I wasn't able to even load the USB installer from OpenCore picker. What I didn't tried was to erase NVRAM before loading the installer. You can give it a try, maybe NVRAM values make windows crash.

**Comment by richardphan01** [comment]
Has anyone figured this out?

**Comment by zombillano** [comment]
> Has anyone figured this out? I can't boot windows at all - using same ssd for both OSes

I didn't but I'm using refind to select which OS to boot. Just install macOS, then windows and then refind, works well on a single SSD.

**Comment by EETagent** [comment]
> Has anyone figured this out? I can't boot windows at all - using same ssd for both OSes

In the F12 boot menu, there should two OS entries. Otherwise you can use rEFInd or GRUB, etc.

**Comment by knee41** [comment]
I have successfully (so far) multi-booted my PC using this tool. Windows initially complained about ACPI, but after a reinstall it booted from open core fine. I tried to switch off the ACPI by chain loading grub from open core and then having ACPI turned off by the grub parameters, but I don't think that did anything all all. I don't think I did anything special.

**Comment by knee41** [comment]
I'm getting the ACPI_BIOS_ERROR again, so I shouldn't have spoken so soon :(

**Comment by richardphan01** [comment]
> > Has anyone figured this out? I can't boot windows at all - using same ssd for both OSes
> 
> In the F12 boot menu, there should be two OS entries. Otherwise you can use rEFInd or GRUB, etc.
> 
> I would like to solve problems with Windows/Linux boot, but I do not know where to start. As I stated above, everything should be correct in this EFI.

There are two entries, but after booting up MacOS after my Windows install, selecting the Windows Partition shows it loading after without the windows logo, then the system restarts

**Comment by zombillano** [comment]
> > > Has anyone figured this out? I can't boot windows at all - using same ssd for both OSes
> > 
> > 
> > In the F12 boot menu, there should be two OS entries. Otherwise you can use rEFInd or GRUB, etc.
> > I would like to solve problems with Windows/Linux boot, but I do not know where to start. As I stated above, everything should be correct in this EFI.
> 
> There are two entries, but after booting up MacOS after my Windows install, selecting the Windows Partition shows it loading after without the windows logo, then the system restarts. I'm also loading through a single ssd so boot menu doesn't work since it sends me to the opencore menu

Don't use opencore to load Windows. Support for that isn't that great from part of acidanthera's group.

You can use refind which is very customizable (you can use different themes, hide unwanted bootable partitions, etc, etc) to choose between loading windows or opencore to load MacOS. On the opencore side you can disable the menu picker on config.plist, just make sure to select your macOS partition as bootable on System Preferences because opencore uses that setting to decide which OS to boot as default.

Because of that I don't think that trying to boot windows from opencore worths the time involved in finding the exact configuration that'll allow it. 

My own personal setup makes refind boot directly to opencore unless there's a key stroke before refind boots, so in that case it shows me a menu to choose between OS. Opencore boots directly to macOS. Takes something around 25-30 seconds to boot all the way to the login screen, which might seems like a lot of time but it isn't that big deal. 

This should change in the future when acidanthera's group decides to focus on loading other OS with opencore. 'Till then I think this would keep unsolved in prior of other bugs that we are still trying to solve.

**Comment by EETagent** [comment]
@zombillano  @knee41  @richardphan01 

> The ACPI_BIOS_ERROR returned again

Because there is definitely something wrong with current ACPI patches, I created [new branch](https://github.com/EETagent/T480-OpenCore-Hackintosh/tree/new-acpi) with ACPI patches from [X1C6](https://github.com/tylernguyen/x1c6-hackintosh). As T480 is almost the same machine as a X1C6 ( Except battery stuff ), macOS booted fine. What is important though, Linux booted fine from OC boot menu too! ( I do not have currently Windows installed ). Can you please try to boot with EFI from this specific branch so we will see if it works and then try to find what is wrong with current ACPI setup? Thanks.

**Comment by zombillano** [comment]
I tried the OC setup that you posted on that branch. I'm unable to boot neither my macOS install or Windows Install. Are you sure that you fixed the battery related ACPI files before pushing that release? It's strange that I'm unable to boot macOS. I tried to boot with those ACPI patches before, do you remember?

**Comment by EETagent** [comment]
@zombillano 
Nope, I did not change anything as I did not have to. Battery patches there are not a problem as we use BAT0 too, there is just not NTFY and BATC for second battery.

**Comment by zombillano** [comment]
I found my issue: I suppose that BAT0 is the internal battery and BAT1 is the external one. My T480 lacks internal battery from factory, so deleting the BAT0 SSDT allowed me to boot successfully on macOS. Windows is still unable to boot. Does this ACPI config has any other "improvement" over the ones we are already using? If so to keep them on my main EFI partition. If not then I'll go back to the 4.0.0 release

**Comment by EETagent** [comment]
> Does this ACPI config has any other "improvement" over the ones we are already using? If so to keep them on my main EFI partition. If not then I'll go back to the 4.0.0 release

No, I just wanted to check if it is possible to boot Windows.

**Comment by EETagent** [comment]
Hi @zombillano, can you please test latest patches in new-acpi?

**Comment by zombillano** [comment]
I can boot to macOS just fine without changing anything, and can confirm that now battery level is pretty accurate. Congrats about it! I can't boot my windows 10 partition, though. I'm using windows LSTC so I'm unsure if it can be the source of this issue (it shouldn't but with this hacks we never know). I will try to create different windows 10 USB installers later today, unfortunately I didn't bring any USB drive with me today, so it will have to wait till I get home. I think that achieve to boot a windows 10 installer from opencore is the first step to achieve this goal, because I wasn't even able to do so before.

**Comment by EETagent** [comment]
That's sad. I thought that it would work now. At least battery is fixed and Linux boots now. I am out of ideas, this would need updated N-D-K OpenCore fork or some skilled ACPI engineer

**Comment by zombillano** [comment]
I'm being unable to put my computer to sleep closing the lid, can you confirm the same behavour?

**Comment by zombillano** [comment]
I think this ACPI patches needs some polishing. Right now I came to my computer after an hour or so of leaving it sleeping and now it doesn't want to increase or reduce the brightness level because it recognizes the display as an external display.

**Comment by EETagent** [comment]
> I'm being unable to put my computer to sleep closing the lid, can you confirm the same behaviour?

Oops, I removed patch which enable this as I did not found it in any other repos and thought it would work without it.

> I think this ACPI patches needs some polishing. Right now I came to my computer after an hour or so of leaving it sleeping and now it doesn't want to increase or reduce the brightness level because it recognizes the display as an external display.

That is weird as there are no changes with PNLF.

**Comment by zombillano** [comment]
> That is weird as there are no changes with PNLF. It is true though, that it's now possible to fully turn off screen using brightness keys which from what I currently remember was not previously possible. It is same SSDT-PNLF-SKL_KBL.aml as before, just recompiled from source.
Strange, then. I've always been able to turn off the screen when lowering the brightness :p So I don't think it is a new feature. I will do some more testing and report back later

**Comment by zombillano** [comment]
Yes, the issue is caused by the new ACPI patches. With the old ACPI patches I can modify brightness just right. For some reason I have a tv on the same network that allows airplay, might be related?

**Comment by EETagent** [comment]
> I'm being unable to put my computer to sleep closing the lid, can you confirm the same behaviour?

 Putting computer to sleep using lid works for me even without using sad hotpatch. Please retest with SSDT-Lid enabled/disabled.

**Comment by zombillano** [comment]
> > I'm being unable to put my computer to sleep closing the lid, can you confirm the same behaviour?
> 
> Putting computer to sleep using lid works for me even without using mentioned hotpatch. Please retest with SSDT-Lid enabled/disabled.

As I said earlier my problem was that I only replaced the ACPI folder and rebuild my config.plist file with ProperTree which doesn't seems to rebuild ACPI submenu. Putting the config.plist file from the new ACPI patches repo solved my issue. Thanks for taking the time to confirm, mate :)

**Comment by EETagent** [comment]
Great to hear that there is some progress. Are Windows stable enough? It did't work with PNLF in master branch? As both are exactly the same ( `Return (Zero)` in current version, but that is definitely not source of this issue )
```
DefinitionBlock ("", "SSDT", 2, "T480", "PNLF", 0x00000000)
{
    Scope (_SB)
    {
        Device (PNLF)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Name (_HID, EisaId ("APP0002"))  // _HID: Hardware ID
            Name (_CID, "backlight")  // _CID: Compatible ID
            Name (_UID, 0x10)  // _UID: Unique ID
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0B)
                }
                Else
                {
                    Return (Zero)
                }
            }
        }
    }
}
```
Master branch
```
DefinitionBlock ("", "SSDT", 2, "T480", "PNLF", 0x00000000)
{
    If (_OSI ("Darwin"))
    {
        Scope (_SB)
        {
            Device (PNLF)
            {
                Name (_ADR, Zero)  // _ADR: Address
                Name (_HID, EisaId ("APP0002"))  // _HID: Hardware ID
                Name (_CID, "backlight")  // _CID: Compatible ID
                Name (_UID, 0x10)  // _UID: Unique ID
                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    Return (0x0B)
                }
            }
        }
    }
}
```
Version above

**Comment by UA3** [comment]
I was using the master branch, the only ACPI prevented windows from booting was PNLF, so I moved "If (_OSI ("Darwin")" to include the whole function, maybe the return value should be 0x0 instead of Zero? I'm not familiar with ACPI patches, probably further testing will be required.

As of now, I booted windows from OC several times in the last hours, and used it for couple of hours with no issues.

**Comment by EETagent** [comment]
@UA3  Thanks, it is always the one you suspect the least. It’s really weird that Return(Zero) has such devastating effect. Probably some weird Windows thing.

**Comment by EETagent** [comment]
Can @zombillano try these change?

**Comment by zombillano** [comment]
> Can @zombillano try these changes?

Yes, it works. Boots as normal. @knee41 please give it a try, so we can have enough proofs in order to close this issue. I don't think it would cause any instability. @EETagent Can you confirm that you are still able to boot into linux with this new change? I suspect that "return(Zero)" might be needed for something, but I'm still unsure for what. Maybe the best approach would be to modify the function and add an else-if sentence that returns nothing if windows is being loaded.

**Comment by EETagent** [comment]
That’s great. This little change is major milestone in the history of this repo. No, I can not boot Linux currently from OC but that is issue on my Linux EFI side ( In the UEFI boot menu, there is ubuntu and NVMe entry. It is possible to boot Linux from ubuntu entry but not from NVMe one, which is what OC finds. I recently compiled and installed 5.9 rc1 kernel and messed with /boot partition ... so that might be reason why it don’t work now ) That is not point of this issue though.

Also, just keep in mind that it might not be a good idea to perform firmware upgrades ( No fwupdmgr nor Vantage ) when booting from OC as TP thinks that he is a MBP, etc. I will put this disclaimer in the README when changes for Windows are pushed

**Comment by zombillano** [comment]
AFAIK it doesn't think it is a MBP because we have configurated it to be that way on config.plist file, right?

**Comment by EETagent** [comment]
> AFAIK it doesn't think it is a MBP because we have configurated it to be that way on config.plist file, right?

Yes, it thinks it is MBP because it's configured in config.plist. OC injects SMBIOS on all platforms ( I think )

Please try these:
`wmic computersystem get model,name,manufacturer,systemtype`
`wmic csproduct get vendor, version`

**Comment by EETagent** [comment]
Fixed SSDT-PNLF in 3953f42

**Comment by zombillano** [comment]
> Yes, it thinks it is MBP because it's configured in config.plist. OC injects SMBIOS on all platforms ( I think, it is for more native Bootcamp experience but I am not exactly sure )

You are right. I tried configuring OC to stop creating a new SMBIOS on each boot which seems to make windows recognize the computer as a T480 BUT battery and some other devices are not being detected properly. I cannot set battery threshold if I boot via OC.

If someone needs to update its firmware/BIOS/etc just boot windows through the F12 boot menu. Otherwise you may encounter issues. 

Said that, if you want to use lenovo vantage you will need to boot either with the F12 boot menu or any other external loader (reFind, for example). If you prefer to get bootcamp like features like choosing which OS to boot from Apple's bootcamp software, while loosing lenovo vantage features, then use OC to load windows.

I think we can close this issue now. Thanks everyone for your help :) 👍

**Comment by EETagent** [comment]
OK, feel free to reopen if there would be some issues again.

**Comment by aleixsr** [comment]
Hello, I'm getting ACPI_BIOS_ERROR when I try to boot Windows 10, can you please help ?
