### ISSUE TITLE
Ambiguity in readme.txt

### ISSUE THREAD

**Issue by knee41** [EETagent/T480-OpenCore-Hackintosh#21]
It is not clear if generating your own SMBIOS is recommended and why. The only instruction to 'generate your own SMBIOS' is in the section describing what is working next to information about the App Store. Is it recommended to get the App Store and iMessage to work? I have installed without issue without custom SMBIOS, but of course that says nothing about whether there are any advantages either way.

**Comment by EETagent** [comment]
Hi, @knee41 

SMBIOS is used as an identifier of a Macintosh.  It is connected to Apple ID used on that machine. Apple may block Apple IDs which are connected to “abused” SMBIOS ( There are no reports if that ever happened, just change it please, it is easy ).  Because of that, it is best practice to have unique one. Please read linked Dortania guide, there is everything important.
