### ISSUE TITLE
Slow processor after update to 10.15.6

### ISSUE THREAD

**Issue by swatchie-1** [EETagent/T480-OpenCore-Hackintosh#24]
Hi. I’m using a T480 with a i5-8350u. 
Initially I installed Catalina 10.15.5 and all is working well.
After updating to 10.15.6 from the system preferences, the problem starts. 

Each time I power up or restart my computer, it will take a long time to boot. I checked the processor power usage, it hardly goes over 12W. 

However if I put it to sleep and wake again, the cpu performance goes back to normal.

I hadtried disabling the cpufriend kexts but the proble, persists. Anything for me to try out? I may need to downgrade back to 10.15.5 again.

Thx

**Comment by EETagent** [comment]
By slow boot you mean 30 sec, 1 min, etc. ? As for me, boot time is relatively normal.

**Comment by swatchie-1** [comment]
it's not only the slow boot. When I'm signed in, the processor does not go above 8 Watts (Intel Power Gadget) and the temperature doesn't go above 50 degrees. But after putting it to sleep and waking, the processor goes back to normal and temperature goes up to 78 degrees.

I think it's the issue of processor scaling during boot. 
Any suggestion to improve the processor?

**Comment by zombillano** [comment]
Try to update your BIOS to the latest available. I'm able to get all the power out of my i7-8650u with untouched OC config from this repo, even when it was originally made for the i5-8250u.

Are you using voltageswift? Make sure to try without it, because it has the capability to disable turbo boost and lock your processor down.

**Comment by swatchie-1** [comment]
Thanks. let me try it now. my bios is 1.3X last i checked.

**Comment by EETagent** [comment]
Bad CPUFriend  profile can also throttle performance. Try to remake it using CPUFriendFriend with this pull request merged https://github.com/corpnewt/CPUFriendFriend/pull/7

**Comment by swatchie-1** [comment]
Hi. Regarding the bios, it's already 1.34 which is the latest version so there's no effect.

Regarding CPU friend, i've used
800MHz for Power saving
1300MHz for balanced
1300MHz for performance.

Maybe slight improvement but temperature still doesn't go above 50 degrees. Still sluggish performance. Will try increasing the CPUFriend again.

**Comment by zombillano** [comment]
1300MHz for balanced and performance is too low, isn't it @EETagent ? Base frequency of your processor is 1700Mhz
![imagen](https://user-images.githubusercontent.com/34992400/89918141-491b8c00-dbbf-11ea-80d7-00eefd077513.png)

Disable voltageswift, CPUFriend and CPUProvider on config.plist file and resetting NVRAM on restart. What's your energy profile setting on BIOS?

**Comment by swatchie-1** [comment]
hi zombillano thanks for your advice. I've disabled cpufriend and cpuprovider and reset nvram too but still doesn't improve the first boot performance. In bios, i also made battery and power adapter as maximum performance.

I also increased the cpufriend to 1700mhz for the Balanced, Power and Performance profile, i then rebooted and reset NVRam. Performance went back to normal once. But the next reboot, it came back again to being sluggish. 

If there's no solution again, i will try to delete everything and reinstall 10.15.5.

**Comment by zombillano** [comment]
I'm running 10.15.6 without any issue, in case you want to make a clean install with that version

**Comment by tienhuynh5312** [comment]
@swatchie-1 try to disable CPUFriend and see. In performance profile should be some things higher. You should put in account that turbo boost clock which is above 3GHz.

**Comment by zombillano** [comment]
@swatchie-1 Were you able to solve it?

**Comment by swatchie-1** [comment]
I just reinstalled through 10.15.6 through the web download. Currently still fine.

I suspect it always happens after I install the Intel Power Gadget from [macupdate.com](https://www.macupdate.com/app/mac/55310/intel-power-gadget)

It's non-reversible after the lag happens. I've tried clover and various other open core for T480 but it still will not go full performance on first boot.

I will update if it happens again. Upon which I may just surrender and install Windows :)

**Comment by tienhuynh5312** [comment]
Intel Power Gadget has bugs since 3.6.x that might send hackintosh into kernel panic mode because there is something wrong EnergyDriver.kext. Use version 3.5.5 instead

**Comment by swatchie-1** [comment]
I'm still having cpu throttling issues on first boot. I'm using HWMonitor and the CPUPackage power does not go above 10W.
After putting it to sleep and back, the power goes back above 20W for tasks, which is snappier.

I've cleanly reinstalled MacOS at least 3 times now. To reproduce the problem its:
1) Clean install 10.15.6
2) Get my iCloud files downloaded
3) Get my Google Drive items downloaded
Then it starts. If I provide my iOREG file here, would it help?

**Comment by zombillano** [comment]
> Intel Power Gadget has bugs since 3.6.x that might send hackintosh into kernel panic mode because there is something wrong EnergyDriver.kext. Use version 3.5.5 instead

Lattest Intel Power Gadget (3.7) solves that issue. Update through Intel Power Gadget -> Check for Updates, somehow that version isn't available on their website. I think it adds GFX average and GFX Req. Give it a try if you want






> I'm still having cpu throttling issues on first boot. I'm using HWMonitor and the CPUPackage power does not go above 10W.

CPU power consumption won't get high without load. Intel Power Gadget has a built in stress test, please give it a try on first boot.

> After putting it to sleep and back, the power goes back above 20W for tasks, which is snappier.

Do you mean sustained 20W with or without load? This build is pretty well optimized in terms of power management. I'm getting ~3W consumption while writing this. So if you are getting sustained 20W without load then you might have a problem.

> I've cleanly reinstalled MacOS at least 3 times now. To reproduce the problem its:
>     1. Clean install 10.15.6
>     2. Get my iCloud files downloaded
>     3. Get my Google Drive items downloaded

I don't use neither iCloud or Google drive. Since you isolated your problem to this 3 steps, why don't you try to see which one is affecting you? 

>        Then it starts. I provide my iOREG file here, would it help?

I don't see anything wrong with your IOREG report file, it looks pretty normal. Let me give it a try with iCloud first. What do you do, do you add your iCloud account and use iCloud drive?

**Comment by tienhuynh5312** [comment]
> Lattest Intel Power Gadget (3.7) solves that issue.

Not really. My desktop hack does have kernel panic when I open it. B360M i7 9700 RX580

**Comment by swatchie-1** [comment]
Hi guys, update here:
1) I've reverted back again to the beginning of my installation through time machine and now it's working normally.
2) I've installed my icloud drive back
3) I didn't install Google Drive as i suspect it may be the culprit. Has anyone tried using google drive on a T480 and working normally after reboot?

**Comment by swatchie-1** [comment]
Update:
I thought it was the google drive but it wasn't
I've just installed XCode and now it happens too. So it's not anything to do with the softwares.
I suspect the CPU Throttle happens at the beginning of the login screen when the fan didn't cool the CPU enough causing a CPU throttle. We then put it to sleep to reset the throttle and the fan kicks in.

I hope it's not a CPU fault. I will try Windows later.

**Comment by EETagent** [comment]
> I've tried clover and various other open core for T480 but it still will not go full performance on first 

Can you please show actual numbers using some stress test like BMW render test in Blender on Cinebench R20?

**Comment by zombillano** [comment]
> > Lattest Intel Power Gadget (3.7) solves that issue.
> 
> Not really. My desktop hack does have kernel panic when I open it. B360M i7 9700 RX580

You are running Big Sur on that setup too, right? Because it works just fine for me on my T480 running 10.15.6. Seems like a lot of things work really different on Big Sur, lol.

> I hope it's not a CPU fault. I will try Windows later.

It looks like a hardware issue to me. I don't think your thinkpad is broken, just maybe try to repaste it? Does your thinkpad has a dGPU (MX150)? Mine doesn't and AFAIK most of the T480 that we have over here doesn't, but I've read reports of thermal issues with that variant of T480, which indeed makes the computer lock down at very low frequencies when getting over the 70 ºC.

Native fan control and battery thresholds is something I've always wanted on this setup, but I'm still too far from being able to implement something like that. Other issues have been appearing every now and then, too, which I believe are more important to solve.

**Comment by tienhuynh5312** [comment]
> You are running Big Sur on that setup too, right? Because it works just fine for me on my T480 running 10.15.6. Seems like a lot of things work really different on Big Sur, lol.

Nope, it is on Catalina lol.

**Comment by swatchie-1** [comment]
After some testing, i figured it's the thermal throttling. I'm currently using
BIOS 1.31.
I've also tried the latest 1.34 previously but it was the same.
There's a forum here mentioning about [T480 throttling issues](https://forums.lenovo.com/t5/ThinkPad-T400-T500-and-newer-T/T480-throttling-and-high-CPU-temps/td-p/4036815?page=1) 

Is there a way to change the thermal throttling curve?

@EETagent I only tested on Geekbench 5 and my score was 750 single core and 2600 multi core.

**Comment by zombillano** [comment]
Only possible via BIOS mod, but there isn't any software way to do it, so hardmod is needed

**Comment by swatchie-1** [comment]
I have a ch341a programmer tool. Not sure if it’s what t480 hardware flashing uses. I used it on my t440p. 
If hardware bios flash can do it, I may be interested to try.

**Comment by zombillano** [comment]
> I have a ch341a programmer tool. Not sure if it’s what t480 hardware flashing uses. I used it on my t440p.
> If hardware bios flash can do it, I may be interested to try.
Yeah, just that one. Give a look at tylerguyen's X1C6 opencore repo, he has a guide on how to do BIOS mod. T480 are pretty similar. I'm waiting for my own ch341a to arrive to give it a try, too

**Comment by swatchie-1** [comment]
Does this CH341A bios mod work for T480? Haven't seen any articles regarding it. The Hex code changes are the same?

**Comment by zombillano** [comment]
> Does this CH341A bios mod work for T480? Haven't seen any articles regarding it. The Hex code changes are the same?
Yes it does and yes, they are the same. Give a look over here
https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/1_README-HARDWAREandBIOS.md

**Comment by swatchie-1** [comment]
I will attempt it and let you know.

**Comment by EETagent** [comment]
At the end of README.md, there is link for Discord where creators of these patches are located. Or Tyler has recently added it. You can also try Ubuntu 20.04 with [throttled](https://github.com/erpalma/throttled) installed ( and Secure Boot ) disabled.

**Comment by swatchie-1** [comment]
Hi guys, thanks alot for your support and advice.
Currently it's working fine after a day's testing.
What i've done is:

1) Flash the bios hardware to get the Advanced Menu. I haven't tweak the settings as per [tylernguyen](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/1_README-HARDWAREandBIOS.md) but after the hardware flash, the fan and processor has been kind to me.

2) I've also installed a new 2242 NVME to re-install MacOS. The stock SSD is now used for windows.

3) I'm using reFind to dual boot. @zombillano you are doing the same too right?

I can close this now.

**Comment by zombillano** [comment]
> Hi guys, thanks alot for your support and advice.
> Currently it's working fine after a day's testing.
> What i've done is:
> 
>     1. Flash the bios hardware to get the Advanced Menu. I haven't tweak the settings as per [tylernguyen](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/1_README-HARDWAREandBIOS.md) but after the hardware flash, the fan and processor has been kind to me.
> 
>     2. I've also installed a new 2242 NVME to re-install MacOS. The stock SSD is now used for windows.
> 
>     3. I'm using reFind to dual boot. @zombillano you are doing the same too right?
> 
> 
> I can close this now.

It was easy? My programmer arrived yesterday and already revived a dead access point that I had lying around :p Kind of interesting that you didn't have to modify anything, since the BIOS mod only unlocks advance menu. I advise you to do some undervolting, it will reduce heat as well as power consumption. I do -115mV CPU/Cache -80mV GPU and can see an improvement of around 8-10ºC.

About your SSD, is it a SN 520? I've already purchased one, I'm waiting for it to arrive, but would be cool to confirm macOS compatibility.

About reFind, yes, I'm doing the exact same but with one SSD only, the main one. Would do triple boot as soon as my 2242 NMVe drive arrives, a linux partition is always helpful. 

Hope your problem remains solved :)

**Comment by swatchie-1** [comment]
Yeah thanks. I've started doing some undervolting. I'm trying out -130mV cpu now. Where do you get the Cache option to undervolt? Yeah gpu is -80mV too.

Nice to see you're making use of your programmer more than just for your laptop. Double boot on a single SSD? I barely have enough for my 256GB on macOS

**Comment by EETagent** [comment]
I am the only one without the mod now :D 

Choosing M2 2242 SSD is really dilemma. WD SN 520 is deadly expensive here, Toshiba RC100 which was the best deal somewhat disappeared from stores, and Sabrent one is not compatible. Lenovo reseller has some rebranded "Lenovo SSD" but its stats are really poor ( Like every NVMe without DRAM cache, that one is the worst from them though ). I am probably gonna buy WD SN750 and find different home for this cursed Samsung.

**Comment by swatchie-1** [comment]
Got mine from China to send over. Costs about usd50 for 256gb. 
Am using Kingspec 256gb nvme 2242. 

You should try out the mod by purchasing the programmer first. 

Only thing missing for me now is the Apple Watch unlock. Need a BCM94360CS2
Am using the basic MacBook Air 2011 airport card. It does have Universal Clipboard and handoff though.

**Comment by zombillano** [comment]
> Yeah thanks. I've started doing some undervolting. I'm trying out -130mV cpu now.

Wow. If it is stable then congrats because you won the sillicon lottery! I can only undervolt up to -125mV using throttlestop on Windows and -115mV with voltageshift on macOS.  

> Where do you get the Cache option to undervolt? Yeah gpu is -80mV too.

I'm unsure if there's that option on the modded BIOS. I was refering to what I use with voltageShift/throttleStop.

> Nice to see you're making use of your programmer more than just for your laptop. 

Yeah, I mean, I wanted to try on a broken device before doing anything to my T480. I heard that it is needed to play with the clip position until you get a proper connection. I will mod my BIOS later today, but I would like to ask you some questions:

1) Does the BIOS chip is located on the same position as on the X1C6?
2) Did you have any problem with the clip? I had to desolder the BIOS chip on my router in order to had a proper connection. I hope I don't have to do that with my T480.

> Double boot on a single SSD? I barely have enough for my 256GB on macOS

Yes, because I use windows every now and then. Sometimes it is often to just open Parallels Desktop and virtualize using my second partition but some others I need all the performance out of my machine, so that's why I'm dualbooting with a single drive. Mine is 500GB, so I'm not constrained in that aspect.



> I am the only one without the mod now :D

Mine's still unmodded. I'm trying to wait for my 2242 SSD to arrive so I don't have to open it twice (I've already broke two plastic tabs :/) but since I don't see any movement on its tracking info I think I will mod mine later today.

> Choosing M2 2242 SSD is really dilemma [...] I am probably gonna buy WD SN750 and find different home for this cursed Samsung.

+1 to the WD SN750. Man, it is stable and quite cheap compared with the Samsung 970 variants. We don't need those crazy speed from the 970 Pro since T480 only has 2X lanes on both of its M.2 sockets. 

There's also the Lexar NM520 which AFAIK is not compatible with macOS so you would need to disable it at boot, but might be cheaper than any of the other options.

**Comment by swatchie-1** [comment]
> * Does the BIOS chip is located on the same position as on the X1C6?
> * Did you have any problem with the clip? I had to desolder the BIOS chip on my router in order to had a proper connection. I hope I don't have to do that with my T480.

1. Yes regarding the position, it is the nearest one to the CPU. The other chip is located far away at the top right corner which belongs to the thunderbolt 3.
2. The clip was ok. No need to desolder. Make sure you remove your internal battery connectors before attempting it.

Ok, i will try voltage shift too.

**Comment by zombillano** [comment]
Thanks mate, I will mod my BIOS later today.

> Ok, i will try voltage shift too.

You don't need it, it is better to do BIOS undervolting and maybe the CPU undervolt offset already includes the cache one

**Comment by EETagent** [comment]
> Yeah, I mean, I wanted to try on a broken device before doing anything to my T480. I heard that it is needed to play with the clip position until you get a proper connection. I will mod my BIOS later today, but I would like to ask you some questions:

Please take some photos, thanks

**Comment by swatchie-1** [comment]
@EETagent Here's the photo of the chip which I connected it to.
@zombillano regarding the bios undervolting, it won't undervolt the CPUCache. I've used Voltage shift for the CPU, CPU Cache and GPU.

Hope it helps.

![IMG_0061](https://user-images.githubusercontent.com/40285586/90839430-15dcb800-e38a-11ea-99bd-fd7415108fef.jpg)
