### ISSUE TITLE
After sleep, the screen no longer lights up,The power is on, but not flashing

### ISSUE THREAD

**Issue by shi4h** [EETagent/T480-OpenCore-Hackintosh#38]
![WX20200925-132803](https://user-images.githubusercontent.com/35167737/94229815-20631200-ff33-11ea-9e95-f0349416a40f.png)

**Comment by EETagent** [comment]
Please provide your hardware info and especially about your SSD

**Comment by zombillano** [comment]
> Please provide your hardware info and especially about your SSD

Do you think it would be good to create an issue report template ?  Also modify the readme to clarify that you need to disable MX150 dGPU.

@shi4h if your thinkpad has a MX150 dGPU please disable it via config.plist file. Also as @EETagent said, please provide your hardware info in order to track down your issue.

**Comment by EETagent** [comment]
Will reopen if hardware info is given
