### ISSUE TITLE
Battery Life Questions

### ISSUE THREAD

**Issue by DaveMGBK** [EETagent/T480-OpenCore-Hackintosh#48]
Hey, I'd like to thank you (and everyone involved) for doing a wonderful job putting everything together. I have a 99% stable T480 Hackintosh! I have the i7-8650 model, the with a multi touch screen, but that obviously isn't applicable here. I was having issue with Heliport and itlwm so I bit the bullet and bought a Broadcom card. That's about it for variations from the folder.

My last concern is the battery life. I know that hackintosh builds aren't always the most power efficient, but I'm not sure if the percentage meter should wear down so fast. With the 23 + 23 battery setup (which I'm currently writing from) I can go from full charge to ~60% in an hour? I assumed the battery life would have been comparable to Linux, as power management was enabled. The batteries in question are failry healthy, and in W10 I had ~7 hours, and ~5.5/6 in Linux. I've used cpufriend and set it to max power save mode, but it doesn't feel any different. 

Am I doing something wrong here? Must I apply some sort of patch? And help would be greatly appreciated.

**Comment by swatchie-1** [comment]
@DaveMGBK do you lose power during sleep as well? at what rate?

**Comment by DaveMGBK** [comment]
I do, I'd go off AC at maybe, 1:00 AM? I get up for work around 6:00 and I'd have lost about ~4 - 6%.

**Comment by swatchie-1** [comment]
Yeah i face the same issue too. 1% per hour at sleep. At first I thought it was because I was using the Apple's airport wifi card instead of the native wifi card. But since you face the same issue, i can rule out the wifi card.

I have a T440P too but it drains only 5% per day at sleep in macOS.

Not sure if zombilano face the same issue.

**Comment by DaveMGBK** [comment]
Yikes. What is your overall battery life?

**Comment by swatchie-1** [comment]
if watch youtube videos, it can last for 4 hours. at normal brightness.

**Comment by EETagent** [comment]
Battery life should be +-1h comparable to stock Linux. Do you have eGPU? Did you tested battery life on Linux again with Wi-Fi card changed? 

For power drain during sleep, test it on Linux with hibernate enabled. I have +- same sleep drain values on both macOS and Linux.

**Comment by DaveMGBK** [comment]
I'm iGPU, and my battery life issues were with stock WiFi, as well as the Broadcom card. I only installed on Saturday. 

And alright - I just installed Power Tools, I'll check it out and get back to you.

**Comment by benbender** [comment]
@DaveMGBK The biggest draws on power are locked CPU-CFG with the stock bios which holds OSX back to go into deeper idle states on the CPU and the missing power management of the Thunderbolt controller. Both issues can easily lead to a power-draw of 2-4W with light usage instead of ~0.8-1W. Everything else is relatively neglectable compared two these issues.

Both issues can be solved but need either compromises or more work:
* The locked CPU-CFG can be unlocked with a patched bios. See https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/1_README-HARDWAREandBIOS.md (Same for T480, I've done it on both machines)
* For the TB-issue: disable the controller completely for testing. It should give you ~1W less power draw alone. Check with https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html

On a sidenote and out of personal interest: could you give me the vendor-/product-id for your display? (As seen in "Displays"-Tab of Hackintool (https://github.com/headkaze/Hackintool)

**Comment by DaveMGBK** [comment]
Thanks, I disabled TB my time on battery jumped up 30 or so minutes. 

Question: @benbender - If you run IO Services, do you have a x86PlatformPlugin listed? I don't see one on mine.

**Comment by swatchie-1** [comment]
Nice tips @benbender. i will try both this weekend.

**Comment by benbender** [comment]
@DaveMGBK What do you mean by "run IO Services"? If you are missing `x86PlatformPlugin` in IOReg, something is seriously broken...

@swatchie-1 Yes, just all of them.

But be aware that the menu, which the patches are enabling, is intended for hw-developers. Its not completely consistent or user-friendly in any way and can render your machine in a state, where you need to reflash the BIOS externally. Be sure to have a good backup from your original BIOS.

**Comment by DaveMGBK** [comment]
@benbender So my CPU shows up as `PR00`, x86 shows up under there, but I'm still going to review and revise my set up.

Without the CPU-CFG being unlocked, am I doomed to terrible power usage?

**Comment by benbender** [comment]
@DaveMGBK pretty much yes. There may be an alternative to hw-patching but I never did it that way: https://nstarke.github.io/0037-modifying-bios-using-ru-efi.html

**Comment by DaveMGBK** [comment]
Yeah, it's in `/EFI/OC/ACPI/`.

**Comment by zombillano** [comment]
> @DaveMGBK pretty much yes. 

Not true. unlocking the CPU-CFG doesn't make a big difference in terms of battery performance, but undervolting certainly does, as well as disabling TB controller. You can undervolt with voltageshift but it i'll be better if you do it via BIOS just because it will remain across OSs and sleep/wake cycles. 

I'm getting like 6-7 hours with a 48Wh setup. I was getting similar battery performance even before BIOS mod.

Another trick may be to disable Turbo Boost while you are running on battery. I don't know why sometimes macOS triggers Turbo Boost at max while I'm running programs that require a little bit more power than usual. If I disable Turbo Boost I'm still able to run those programs quite well.

That is a macOS behavour, I suffered from it on my real MBP too. Windows seems to manage Turbo Boost in a less aggressive way.

AFAIK @EETagent and @benbender already fixed hibernation issues on latest commit, at least that's what I understood. I have 1% per hour battery drain while sleep, too, but I'm on an old release (not that old but not the latest).

**Comment by benbender** [comment]
@zombillano If so, its pure luck and/or your usage-pattern. PM wont work completely/reliably without MSR 0xE2 (aka CFG-Lock) accessible. You likely won't reach C-States below 6 (if even) without working PM. And yeah, sure you could disable cores, disable turbo etc and it wont be as power hungry.

For the power draw on sleep: I have a theory and may come up with smth to get below that usual 1% (hint: OSX does handle sleep-states for PCI differently on several devices)

**Comment by DaveMGBK** [comment]
Hey guys, one more question: Are my power management issues in any way related to this issue I have where shutting down the machine turns into a reboot?

**Comment by EETagent** [comment]
> 
> 
> Hey guys, one more question: Are my power management issues in any way related to this issue I have where shutting down the machine turns into a reboot?

There is certainly something wrong with your configuration / machine. Try to remake your config from latest master.

**Comment by EETagent** [comment]
Closed as stale
