### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by diegolinhares** [EETagent/T480-OpenCore-Hackintosh#59]
Hi, it's my first time trying to do Hackintosh on my T480.

I follow the installation guides [using Windows](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html) and for the EFI folder, I've used your files.

I reboot and installed OSX on my SSD, after the installation reboot, I can't see my SSD on Open core with OSX to select. 

I can see only when I enter the recovery.

What I'm missing?

**Comment by EETagent** [comment]
Which SSD you use? PM981? Did installation finished successfully or it resulted in kernel panic? What can you see in OC boot menu?

**Comment by diegolinhares** [comment]
Hi my SSD is Samsung MZVLB256HBHQ. I try to format it using the Disk Utility, it starts, but, the notebook reboots. And I try to install again.

I followed these steps:

1 - Downloaded last stable Open Core (0.6.3).

2 - Used the macrecovery script to take the two needed files.

3 - Created a folder to these two files on the root of an USB sticker.

4 - Created a EFI folder on the USB sticker root and pasted your files.

Do you think I did something wrong?

**Comment by EETagent** [comment]
>Hi my SSD is Samsung MZVLB256HBHQ. I try to format it using the Disk Utility, it starts, but, the notebook reboots

Yes, that's PM981. If ThinkPad reboots during disk formatting or during installation, it's perfectly normal PM 981 behaviour. That drive is simply not compatible with macOS, I did not have success with it either so I bought compatible drive instead.

NVMeFix solves this for few people, but because you use this repo, I suposse you have it already enabled.

Unfortunately, nothing can be done about it. You may have success with copying existing installation from compatible drive to PM 981 using program like Clonezilla. While I still had the disk, it "worked" but was heavily unstable.

**Comment by diegolinhares** [comment]
I see, thank you for the help. I think I'll buy the same SSD as yours.
